export enum PURCHASE_ERROR {
  PURCHASE_NOT_FOUND = 'PURCHASE_NOT_FOUND',
  AUTH_CODE_IS_INCORRECT = 'AUTH_CODE_IS_INCORRECT',
  COUNT_GREATER_MAXIMUM = 'COUNT_GREATER_MAXIMUM',
  LENGTH_GREATER_MAXIMUM = 'LENGTH_GREATER_MAXIMUM',
}
