API:
  PORT: 4000

DATABASE:
  TYPE: 'postgres'
  SYNCHRONIZE: true

JWT:
  EXPIRES_IN: '99999h'
  SECRET: 'FKdksk12l3ldlsfdlLlsdll123l05kgjgk04jdkgn6kk2d0fkgsdk32ldovyjkxg'

CACHE:
  HOST: 'ec2-44-194-122-143.compute-1.amazonaws.com'
  PORT: 27889
  PASSWORD: 'pdeb811685305cf8c1bb28d6541d08d8b84190ca075f7189558595b5848891508'
  TTL: 6000000

AWS:
  SECRET_ACCESS_KEY: '24Ev6ozqxt5riFzlnZmZEyWjQ2lh9jRyeLwMixWr'
  ACCESS_KEY_ID: 'AKIAY5PKV7HJOECSKA6G'
  REGION: 'us-east-2'
  BUCKET_NAME: 'laforme'
  ACL: 'public-read'

MAIL:
  EMAIL: 'laformecompany@gmail.com'
  PASSWORD: 'laformecompany12'
  HOST: 'smtp.gmail.com'

FACEBOOK:
  # CLIENT_ID: '168878955342230'
  # CLIENT_SECRET: 'd8b62ef1da6ba65940f90f373d4463b1'
  CLIENT_ID: '201675022064842'
  CLIENT_SECRET: 'e1ace87ecee2d68da565f977d0db0eb6'
  CALLBACK_URL: 'https://laform-api.herokuapp.com/auth/facebook/redirect'

GOOGLE:
  CLIENT_ID: '857571824635-s9u3bhlc806ullpgiib8d626csnjh0de.apps.googleusercontent.com'
  CLIENT_SECRET: 'ENwlRXt3vnRohU8hFNbAcQjf'
  CALLBACK_URL: 'https://laform-api.herokuapp.com/auth/google/redirect'

APPLE:
  CLIENT_ID: 'laform-api.herokuapp'
  KEY_ID: 'NWKUX58DQR'
  TEAM_ID: '59862PVTZ2'
  CALLBACK_URL: 'https://laform-api.herokuapp.com/auth/apple/redirect'

PAY_ANY_WAY:
  MNT_ID: '72511945'
  MNT_INTEGRITY_CODE: 'LF5492769db'
  PAY_URL: 'https://payanyway.ru/assistant.htm?'

CLIENT:
  URL: 'https://laform-client.herokuapp.com'
