API:
  PORT: 4000

DATABASE:
  TYPE: 'postgres'
  SYNCHRONIZE: true

JWT:
  EXPIRES_IN: '99999h'
  SECRET: 'FKdksk12l3ldlsfdlLlsdll123l05kgjgk04jdkgn6kk2d0fkgsdk32ldovyjkxg'

CACHE:
  HOST: 'ec2-44-196-89-67.compute-1.amazonaws.com'
  PORT: 21739
  PASSWORD: 'pdeb811685305cf8c1bb28d6541d08d8b84190ca075f7189558595b5848891508'
  TTL: 6000000

AWS:
  SECRET_ACCESS_KEY: '37T4L1AKRY0tAtJXC7b+FmOCEUFVOoyeMSCx0TGr'
  ACCESS_KEY_ID: 'AKIAIE6IJHPEO346SJ7Q'
  REGION: 'us-east-2'
  BUCKET_NAME: 'testdownloadimagesbucket'
  ACL: 'public-read'

MAIL:
  EMAIL: 'laformecompany@gmail.com'
  PASSWORD: 'laformecompany12'
  HOST: 'smtp.gmail.com'

FACEBOOK:
  CLIENT_ID: '168878955342230'
  CLIENT_SECRET: 'd8b62ef1da6ba65940f90f373d4463b1'
  CALLBACK_URL: 'https://laform-api.herokuapp.com/auth/facebook/redirect'

GOOGLE:
  CLIENT_ID: '857571824635-s9u3bhlc806ullpgiib8d626csnjh0de.apps.googleusercontent.com'
  CLIENT_SECRET: 'ENwlRXt3vnRohU8hFNbAcQjf'
  CALLBACK_URL: 'https://laform-api.herokuapp.com/auth/google/redirect'
