export enum USER_VERIFICATION_ERROR {
  USER_VERIFICATION_EMAIL_ALREADY_CONFIRMED = 'USER_VERIFICATION_EMAIL_ALREADY_CONFIRMED',
  USER_VERIFICATION_EMAIL_CODE_DOESNT_EXISTS = 'USER_VERIFICATION_EMAIL_CODE_DOESNT_EXISTS',
  VERIFICATION_CODE_PAYLOAD_HAS_WRONG_EMAIL = 'VERIFICATION_CODE_PAYLOAD_HAS_WRONG_EMAIL',
}
