export enum AUTH_ERROR {
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  UNCORRECT_PASSWORD_OR_LOGIN = 'LOGIN_UNCORRECT_PASSWORD_OR_LOGIN',
  UNCORRECT_CURRENT_PASSWORD = 'AUTH_UNCORRECT_CURRENT_PASSWORD',
  COULDNT_FOUND_USER = 'LOGIN_COULDNT_FOUND_USER',
  USERNAME_ALREADY_EXISTS = 'SIGN_UP_USERNAME_ALREADY_EXISTS',
  USER_ALREADY_EXISTS = 'INVITE_USER_ALREADY_EXISTS',
  USER_WITH_THIS_ID_NOT_FOUND = 'USER_WITH_THIS_ID_NOT_FOUND',
  AUTH_CODE_IS_INCORRECT = 'OTHER.INCORRECT_CODE',
  UPDATE_OLD_CODE_INCORRECT = 'UPDATE_OLD_CODE_INCORRECT',
  UPDATE_NEW_CODE_INCORRECT = 'UPDATE_NEW_CODE_INCORRECT',
  CODES_IS_INCORRECT = 'CODES_IS_INCORRECT',
}
