export enum USER_ERROR {
  USER_WITH_THIS_ID_NOT_FOUND = 'USER_WITH_THIS_ID_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  MAIL_ALREADY_LINKED_TO_THIS_ACCOUNT = 'MAIL_ALREADY_LINKED_TO_THIS_ACCOUNT',
}
